version: '3.8'

services:
  pubsub-app:
    build: .
    image: saridga/biu-pubsub-app:latest
    container_name: pubsub-monolith
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    stdin_open: true
    tty: true